************************ SQL ************************

RETRIEVE DATA USING THE SQL SELECT STATEMENT
  * SELECT

RESTRICTED AND SORTED DATA
  * WHERE
    * MAIOR QUE: >
    * MAIOR IGUAL À: >=
    * MENOR QUE: <
    * MENOR IGUAL À: <=
    * IGUAL À: =
    * DIFERENTE: !=
    * ESTEJA EM: IN
    * CONTENHA: LIKE
    * NEGAÇÃO: NOT

  * OPERADORES
    * AND
    * OR

  * ORDENAÇÕES
    * ORDER BY
    * DESC / ASC

  * LIMITAÇÕES
      * FETCH FIRST 10 ROWS ONLY
      * OFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY

USAGE OF SINGLE-ROW FUNCTIONS TO CUSTOMIZE OUTPUT
  * NUMÉRICAS:
    * CEIL (VALOR)
    * FLOOR (VALOR)
    * MOD (VALOR, DIVISOR)
    * REMAINDER (VALOR, DIVISOR)
    * POWER (VALOR, POTENCIA)
    * ROUND (VALOR, DECIMAL)
    * TRUNC (VALOR, DECIMAL)
    * SQRT (VALOR)

  * CARACTER:
    * RETORNANDO CARACTER
      * CHR (NUMERO)
      * CONCAT (PALAVRA1, PALAVRA2)
      * INITCAP (PALAVRA)
      * LOWER (PALAVRA)
      * UPPER (PALAVRA)
      * UPPER (PALAVRA)
	  * Oracle: RTRIM( ), LTRIM( )
      * TRIM (PALAVRA) - TRIM ([LEADING | TRAILING | BOTH] CARACTER FROM PALAVRA)
      * SUBSTR (PALAVRA, INICIO, QUANTIDADE)

    * RETORNANDO NÚMERO
      * INSTR (PALAVRA, PESQUISA, INICIO, QUANTIDADE)
      * ASCII (NUMERO)
      * LENGTH (PALAVRA)
      * REGEXP_LIKE (PALAVRA, EXPRESSÃO)
      * REGEXP_INSTR (PALAVRA, EXPRESSÃO)

  * DATA E HORA:
    * ADD_MONTHS (DATA, QUANTIDADE)
    * CURRENT_DATE
    * CURRENT_TIMESTAMP
    * EXTRACT
    * LAST_DAY
    * MONTHS_BETWEEN
    * NEXT_DAY
    * ROUND
    * TRUNC
    * SYSDATE
    * SYSTIMESTAMP
    * TO_CHAR

  * COMPARATIVO
    * GREATEST
    * LEAST

  * NULL
    * COALESCE
    * NVL

  * CASE

CONVERSION FUNCTIONS AND CONDITIONAL EXPRESSIONS
  * CAST
  * CONVERT
  * TO_CHAR
  * TO_NUMBER
  * TO_DATE

AGGREGATED DATA USING THE GROUP FUNCTIONS
  * MIN
  * MAX
  * SUM
  * COUNT
  * AVG
  * ROLLUP
  * CUBE

DISPLAY DATA FROM MULTIPLE TABLES
  * JOIN
  * LEFT JOIN
  * RIGHT JOIN
  * FULL OUTER JOIN

USAGE OF SUBQUERIES TO SOLVE QUERIES

SET OPERATORS
  * UNION
  * UNION ALL
  * INTERSECT
  * MINUS

DATA MANIPULATION
  * TRANSAÇÕES
  * INSERT
  * UPDATE
  * DELETE
  * TRUNCATE
  * SELECT FOR UPDATE

DDL STATEMENTS TO CREATE AND MANAGE TABLES
  * DATA TYPES
    * CHAR (BYTES)
    * VARCHAR2 (BYTES|CHAR)
    * NUMBER (ESCALA, PRECISAO)
    * DATE
    * TIMESTAMP (PRECISAO) [WITH LOCAL TIMEZONE]
    * BLOB
    * CLOB
    * NCHAR
    * NVARCHAR
    * INTERVAL YEAR (PRECISAO) TO MONTH
    * INTERVAL DAY (PRECISAO) TO SECOND (PRECISAO)

  * CREATE TABLE
  * CONSTRAINT
    * NOT NULL
    * FOREIGN KEY
    * CHECK
    * UNIQUE
    * PRIMARY KEY

  * ALTER TABLE
  * RENAME TABLE
  * DROP TABLE

OTHER SCHEMA OBJECTS
  * EXPLAIN PLAN
    * PLAN_TABLE
      * @$ORACLE_HOME/RDBMS/ADMIN/UTLXPLAN.SQL
    * TOOLS
  * TEMPORARY TABLE
  * INDEX
  * SEQUENCE
  * SYNONYM
  * VIEW
  * TRIGGER
  * ROLE
    * GRANT
    * REVOKE


************************ PL/SQL ************************
INTRODUCTION TO PL/SQL
  * VANTAGES E DESVANTAGENS

PL/SQL IDENTIFIERS
  * := ATRIBUIÇÃO
  * => ASSOCIAÇÃO
  * || CONCATENAÇÃO
  * ** EXPONENCIAL
  * << LABEL DELIMITER (BEGIN)
  * >> LABEL DELIMITER (END)
  * /* MULTI-LINE COMMENT DELIMITER (BEGIN)
  * */ MULTI-LINE COMMENT DELIMITER (END)
  * .. RANGE OPERATOR
  * <> RELATIONAL OPERATOR
  * != RELATIONAL OPERATOR
  * <= RELATIONAL OPERATOR
  * >= RELATIONAL OPERATOR
  * -- SINGLE-LINE COMMENT INDICATOR
  * + ADIÇÃO
  * % RESTO DA DIVISÃO
  * ' LIMITADOR DE CARACTER
  * . SELETOR
  * / DIVISÃO
  * ( EXPRESSION OR LIST DELIMITER
  * ) EXPRESSION OR LIST DELIMITER
  * : HOST VARIABLE INDICATOR
  * , ITEM SEPARATOR
  * * MULTIPLICATION OPERATOR
  * " QUOTED IDENTIFIER DELIMITER
  * = RELATIONAL OPERATOR
  * < RELATIONAL OPERATOR
  * > RELATIONAL OPERATOR
  * @ REMOTE ACCESS INDICATOR
  * ; STATEMENT TERMINATOR
  * - SUBTRACTION/NEGATION OPERATOR

WRITE EXECUTABLE STATEMENTS
  * BLOCO PL/SQL
  * DBMS_OUTPUT

DESIGN CONSIDERATIONS FOR PL/SQL CODE
  * NOMENCLATURAS
  * VARIÁVEIS
  * CONSTANTES - NOME CONSTANT DATA_TYPE
  * CÓDIGO FONTE

STORED PROCEDURES AND FUNCTIONS
  * PROCEDURE
  * FUNCTION

PACKAGES
  * BENEFÍCIOS

EXCEPTION HANDLING
  * CATEGORIAS DE EXCEÇÕES
    * INTERNALLY DEFINITION
      * DECLARAR UMA VARIÁVEL EXCEPTION
      * ASSOCIAR AO ERROR_CODE, PRAGMA EXCEPTION_INIT (NOME_DA_VARIAVEL, ERROR_CODE)

    * PREDEFINED
      * ACCESS_INTO_NULL        -6530
      * CASE_NOT_FOUND          -6592
      * COLLECTION_IS_NULL      -6531
      * CURSOR_ALREADY_OPEN     -6511
      * DUP_VAL_ON_INDEX        -1
      * INVALID_CURSOR          -1001
      * INVALID_NUMBER          -1722
      * LOGIN_DENIED            -1017
      * NO_DATA_FOUND           -100
      * NO_DATA_NEEDED          -6548
      * NOT_LOGGED_ON           -1012
      * PROGRAM_ERROR           -6501
      * ROWTYPE_MISMATCH        -6504
      * SELF_IS_NULL            -30625
      * STORAGE_ERROR           -6500
      * SUBSCRIPT_BEYOND_COUNT  -6533
      * SUBSCRIPT_OUTSIDE_LIMIT -6532
      * SYS_INVALID_ROWID       -1410
      * TIMEOUT_ON_RESOURCE     -51
      * TOO_MANY_ROWS           -1422
      * VALUE_ERROR             -6502
      * ZERO_DIVIDE             -1476

    * USER-DEFINED
      * DECLARAR UMA VARÍAVEL EXCEPTION

  * EXCEPTION BLOCK

  * RAISING EXCEPTION EXPLICITY
    * RAISE
    * RAISE_APPLICATION_ERROR

  * FUNÇÕES
    * SQLERRM
    * SQLCODE

CONTROL STRUCTURES
  * IF, IF ELSE, IF ELSIF ELSE
  * CASE
  * LOOP, WHILE, FOR

USAGE OF COMPOSITE DATA TYPES
  * SQL DATA TYPE
  * BOOLEAN
  * PLS_INTEGER

EXPLICIT CURSORS
  * DECLARAÇÃO DO CURSOR
  * TRABALHANDO COM O CURSOR
  * CURSOR COM FOR

DYNAMIC SQL
  * EXECUTE IMMEDIATE
  * DBMS_SQL

TRIGGERS
  * EVENTO
    * BEFORE
    * AFTER

  * TIPO
    * DML
      * INSERT
      * UPDATE
      * DELETE
    * VIEWS
      * INSTEAD OF
        * INSERT
        * UPDATE
        * DELETE
    * SYSTEM
      * DDL
      * DATABASE EVENT

MANAGE DEPENDENCIES
  * [DBA|ALL|USER]_DEPENDENCIES
  * %TYPE
  * %ROWTYPE
  * CLÁUSULA INSERT
  * [DBA|ALL|USER]_OBJECT_SIZE

SCHEDULERS
  * FREQUENCIA
    * FREQ=YEARLY | MONTHLY | WEEKLY | DAILY | HOURLY | MINUTELY | SECONDLY
    * REPEAT_INTERVAL=FREQ=VALUE;BYMONTH=N;BYWEEKNO=N;BYYEARDAY=N;BYMONTHDAY=N;BYDAY=N;BYHOUR=N;BYMINUTE=N;BYSECOND=N
  * JOB
  * SCHEDULER
  * PROGRAM
    * PLSQL_BLOCK
    * STORED_PROCEDURE
    * EXECUTABLE
  * JOB_CLASS
  
  
  TITLE: Deselect objects with errors?
------------------------------

Update failed and no objects were modified.
		
		If you confirm, GeneXus will automatically deselect the objects with errors, so you may retry a new update that doesn't include them (use the 'Update Selected' button in the 'Preview' tab).
		
		Do you want to deselect the objects with errors?

------------------------------
BUTTONS:

Yes
No
------------------------------
